<?php

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) exit;


// Verify for Payout ID
if ( empty( $_GET['payout_id'] ) )
	exit;

// Get the payment information
$payout = slicewp_get_payout( absint( $_GET['payout_id'] ) );

if( is_null( $payout ) )
	return;

// Get the admin that generated the payout
$admin = get_user_by( 'id', $payout->get('admin_id') );

// Get the Payout Payments Count
$args = array(
	'payout_id' => $payout->get('id')
);

$payments_count = slicewp_get_payments( $args, true );

// Get the Payout Payments Count for paid Payments
$args = array(
	'payout_id' => $payout->get('id'),
	'status'	=> 'paid'
);

$payments_paid_count = slicewp_get_payments( $args, true );

// Compute the Paid percentage
$paid_percentage = round( $payments_paid_count / $payments_count * 100 );

?>

<div class="wrap slicewp-wrap slicewp-wrap-view-payout">

	<!-- Page Heading -->
	<h1 class="wp-heading-inline"><?php echo sprintf( __( 'Payout #%s', 'slicewp' ), $payout->get('id') ); ?></h1>
	<a href="<?php echo add_query_arg( array( 'subpage' => 'create-payout' ), $this->admin_url ); ?>" class="page-title-action"><?php echo __( 'Create Payout', 'slicewp' ); ?></a>
	<a href="<?php echo add_query_arg( array( 'subpage' => 'view-payments' ), $this->admin_url ); ?>" class="page-title-action"><?php echo __( 'All Payments', 'slicewp' ); ?></a>
	<hr class="wp-header-end" />
	
	<div id="slicewp-content-wrapper">
			
		<!-- Primary Content -->
		<div id="slicewp-primary">

			<!-- Payout Details -->
			<div class="slicewp-card slicewp-first">

				<div class="slicewp-card-header">
					<?php echo __( 'Payout Details', 'slicewp' ); ?>
				</div>

				<!-- Form Fields -->
				<div class="slicewp-card-inner">

					<!-- Payout ID -->
					<div class="slicewp-field-wrapper slicewp-field-wrapper-inline">

						<div class="slicewp-field-label-wrapper">
							<label for="slicewp-payout-id"><?php echo __( 'Payout ID', 'slicewp' ); ?></label>
						</div>
						
						<input id="slicewp-payout-id" name="payout_id" disabled type="text" value="<?php echo esc_attr( $payout->get('id') ); ?>" />

					</div>

					<!-- Amount -->
					<div class="slicewp-field-wrapper slicewp-field-wrapper-inline">

						<div class="slicewp-field-label-wrapper">
							<label for="slicewp-payout-amount"><?php echo __( 'Amount', 'slicewp' ); ?></label>
						</div>

						<input id="slicewp-payout-amount" name="amount" disabled type="text" value="<?php echo esc_attr( slicewp_format_amount( $payout->get('amount'), slicewp_get_setting( 'active_currency', 'USD' ) ) ); ?>" />

					</div>
					
		            <!-- Payments Count -->
					<div class="slicewp-field-wrapper slicewp-field-wrapper-inline">

						<div class="slicewp-field-label-wrapper">
							<label for="slicewp-payments-count"><?php echo __( 'Payments', 'slicewp' ); ?></label>
						</div>
						
						<input id="slicewp-payments-count" name="payments_count" disabled type="text" value="<?php echo esc_attr( $payments_count ); ?>" />

					</div>
					
		            <!-- Payout Date -->
					<div class="slicewp-field-wrapper slicewp-field-wrapper-inline">

						<div class="slicewp-field-label-wrapper">
							<label for="slicewp-payout-date"><?php echo __( 'Date Created', 'slicewp' ); ?></label>
						</div>
						
						<input id="slicewp-payout-date" name="date_created" disabled type="text" value="<?php echo slicewp_date_i18n( esc_attr( $payout->get('date_created') ) ); ?>" />

					</div>

					<!-- Generated By -->
					<div class="slicewp-field-wrapper slicewp-field-wrapper-inline slicewp-last">

						<div class="slicewp-field-label-wrapper">
							<label for="slicewp-generated-by"><?php echo __( 'Generated By', 'slicewp' ); ?></label>
						</div>

						<div class="slicewp-field-link-disabled">
							<?php if( null === $admin ): ?>
								<span><?php echo __( '(inexistent admin)', 'slicewp' ); ?></span>
							<?php else: ?>
								<a href="<?php echo add_query_arg( array( 'user_id' => $payout->get('admin_id') ), admin_url( 'user-edit.php' ) ); ?>"><?php echo $admin->first_name . ' ' . $admin->last_name . ' ('. $admin->user_login . ')'; ?></a>
							<?php endif; ?>
						</div>

					</div>

				</div>

			</div><!-- / Payout Details -->

			<!-- Payout Progress -->
			<form method="POST">

				<div class="slicewp-card slicewp-first">

					<div class="slicewp-card-header">
						<?php echo __( 'Payout Progress', 'slicewp' ); ?>
					</div>

					<div class="slicewp-card-inner">

		                <!-- Progress -->
						<div class="slicewp-field-wrapper slicewp-last">
							
							<?php slicewp_output_progressbar( $paid_percentage ); ?>

						</div>

					</div>

					<?php if( slicewp_can_do_bulk_payments( $payout->get( 'id' ) ) ): ?>
						<div class="slicewp-card-footer">

							<div class="slicewp-field-wrapper slicewp-field-wrapper-payout-method slicewp-last">

								<div class="slicewp-flex-wrapper">

									<?php $payout_methods = slicewp_get_payout_methods(); ?>

									<select class="slicewp-select2" name="payout_method">

										<option value=""><?php echo __( 'Select payout method...', 'slicewp' ); ?></option>

										<?php foreach( $payout_methods as $payout_method_slug => $payout_method ): ?>

											<?php if( empty( $payout_method['supports'] ) || ! in_array( 'bulk_payments', $payout_method['supports'] ) ) continue; ?>

											<option value="<?php echo esc_attr( $payout_method_slug ); ?>"><?php echo $payout_method['label']; ?></option>

										<?php endforeach; ?>

									</select>

									<button class="slicewp-button-primary" disabled>
										<span class="slicewp-button-label slicewp-button-label-manual"><?php echo __( 'Mark as Paid', 'slicewp' ); ?></span>
										<span class="slicewp-button-label slicewp-button-label-other"><?php echo __( 'Pay Affiliates', 'slicewp' ); ?></span>
									</button>

								</div>

							</div>

							<input type="hidden" name="payout_id" value="<?php echo absint( $payout->get('id') ); ?>" />
							<input type="hidden" name="slicewp_action" value="do_bulk_payments" />
							<?php wp_nonce_field( 'slicewp_do_bulk_payments', 'slicewp_token', false ); ?>

						</div>
					<?php endif; ?>

				</div>

			</form><!-- / Payout Progress -->

			<form method="GET">

				<!-- Payouts List Table -->
				<?php 
					$table = new SliceWP_WP_List_Table_Payout_Payments();
					$table->views();
					$table->display();
				?>

				<!-- Hidden fields needed for the search query -->
				<input type="hidden" name="page" value="slicewp-payouts">

			</form>

		</div><!-- / Primary Content -->

		<!-- Sidebar Content -->
		<div id="slicewp-secondary">

			<?php 

				/**
				 * Hook to add extra cards if needed in the sidebar
				 *
				 */
				do_action( 'slicewp_view_payouts_view_payout_secondary' );

			?>

		</div><!-- / Sidebar Content -->

	</div>

</div>